### ISSUE TITLE
jugendliche Mitglieder

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/Dokumente#13]
Die Satzung kennt neben ordentlichen Mitgliedern und Fördermitglieder auch Jugendliche Mitglieder.
Im Mitgliedsantrag und im praktischen Leben finden sich nur zwei, ordentliches Mitglied, Fördermitglied.

Wahlrecht und Höhe des Mitglidsbeitrags sind jedeoch altersabhängig. Dies sollte auch so in der Satzung wiedergegeben sein.

**Comment by IVI053** [comment]
Das Stimmrecht sollte nicht an die Mitgliedschaft gebunden werden, sondern allgemein an das Alter der stimmrechtausübenden Person. Damit wäre auch die Stimmrechtsübertragung abgesichert.
