### ISSUE TITLE
Satzung: §7 Nr. 3 und § 8 Nr. 4. erzeugen einen infinite loop

### ISSUE THREAD

**Issue by IVI053** [fablabnbg/Dokumente#17]
Beide Absätze verweisen aufeinander mit den selben Rechten und Pflichten.

**Comment by Hobo2k** [comment]
Entweder ist MV oder Vorstand für alles andere was nicht definiert ist verantwortlich.
Ich wäre für den Vorstand sonst braucht man häufiger die MV.

**Comment by jnweiger** [comment]
Genau. Executive/Operative ZUständigkeit => Vorstand, 
Legislative Zuständigkeit => MV, oder so...

**Comment by jnweiger** [comment]
Satzung sagt: MV ist das oberste beschlussfassende Vereinsorgan
Satzung sagt: Der Vorstand wird von der Mitgliederversammlung ... gewählt

Damit ist die Hierarchie hinreichend klar. Oder nicht?

**Comment by IVI053** [comment]
Hierarchie ja, aber irgendwie ist es trotzdem ein Aufeinanderzeigen ohne klare Definition. Vermutlich aber nicht bis zur MV 2016 zu beheben.
