### ISSUE TITLE
Mitglied+ Mitglieder den Fördermitgliedern gleichstellen

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/Dokumente#26]
Aktuell kann nur das stimmberechtigte Mitglied aus einer Mitgliedschaft+ sicher an der MV teilnehmen. Alle anderen Personen einer Mitgliedschaft+ müssen auf die Zulassung von Gästen hoffen.

**Comment by IVI053** [comment]
Mitglied+ wurde bei der letzten MV in der Beitragsordnung gestrichen. Somit ist das Thema obsolet
