### ISSUE TITLE
Neues Wahlsystem für Vorstandswahlen?

### ISSUE THREAD

**Issue by IVI053** [fablabnbg/Dokumente#32]
Da bisher meist sehr viele Wahldurchgänge nötig waren, möchte ich ein Präferenzwahlsystem vorschlagen.

Vorschläge:

- https://de.wikipedia.org/wiki/Instant-Runoff-Voting
- https://de.wikipedia.org/wiki/%C3%9Cbertragbare_Einzelstimmgebung

Meinungen?

**Comment by Hobo2k** [comment]
Sehr viele? Vor 3 Jahren war es einer für die Wahl und einer für den Vorstandsvorsitzenden, letztes Jahr 2 Durchgänge und einen für die Vorstandsvorsitzenden.

ich finde diese Rechenverfahren machen es komplizierter.
