### ISSUE TITLE
Make: Unkown Reader: markdown_github

### ISSUE THREAD

**Issue by Hobo2k** [fablabnbg/Dokumente#33]
@jnweiger 
Im Makefile fehlen scheinbar Pakte oder so:

`$ make
pandoc --standalone -f markdown_github -t html -V mainfont=sans -o build/Satzung.html Satzung.md
pandoc: Unknown reader: markdown_github
Makefile:20: recipe for target 'Satzung.html' failed
make: *** [Satzung.html] Error 7
`

Könntest du das mal verifizieren? Danke.

**Comment by jnweiger** [comment]
Testmer mal:
```
sudo apt install pandoc texlive-xetex texlive-fonts-recommended lmodern
make Satzung.pdf
xdg-open build/Satzung.pdf
```
Funktioniert wunnerbar hier.
Mein pandoc sagt
```
$ pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /home/testy/.pandoc
$ pandoc --list-input-formats | grep markdown
markdown
markdown_github
markdown_mmd
markdown_phpextra
markdown_strict
```
Neuerers pandoc kann `gfm` anstatt `markdown_github` -- vielleicht gehts dann?

**Comment by Hobo2k** [comment]
Also bei mir gehts nicht. Eine neuere Pandoc bekomm ich auch nicht installiert...

 pandoc --version
pandoc 1.9.4.2
Compiled with citeproc-hs 0.3.4, texmath 0.6.0.6, highlighting-kate 0.5.1.

Ich habe nur folgende Formate scheinbar:
Input formats:  native, json, markdown, markdown+lhs, rst, rst+lhs, docbook,
                textile, html, latex, latex+lhs

Auch gfm bringt unkown reader.


Zusatz:
 $ apt-cache showpkg pandoc
Package: pandoc
Versions:
1.9.4.2-2 (/var/lib/apt/lists/mirrordirector.raspbian.org_raspbian_dists_wheezy_main_binary-armhf_Packages) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/mirrordirector.raspbian.org_raspbian_dists_wheezy_main_binary-armhf_Packages
                  MD5: 2def94f76ac781452bda44b048aa1e1c


Reverse Depends:
  doconce,pandoc
Dependencies:
1.9.4.2-2 - libbibutils2 (2 4.12) libc6 (2 2.13-28) libffi5 (2 3.0.9) libgcc1 (2 1:4.4.0) libgmp10 (0 (null)) libpcre3 (2 8.10) zlib1g (2 1:1.1.4) texlive-latex-recommended (0 (null)) texlive-xetex (0 (null)) texlive-luatex (0 (null)) libghc-citeproc-hs
-data (0 (null))
Provides:
1.9.4.2-2 -
Reverse Provides:
$

**Comment by Hobo2k** [comment]
Okay, installing in an onther envirement with another debian, works.
Issue is the pandoc version.

In the other envirement, I needed also a free textstyle file to install.

Thanks.

**Comment by jnweiger** [comment]
Great that it works for yo now!
What is a free textstyle file? How is it installed?

**Comment by Hobo2k** [comment]
Einfach per apt-get install fonts-freefont-ttf
Das Fonts Paket installieren.
