### ISSUE TITLE
Falsche formatierung.

### ISSUE THREAD

**Issue by Hobo2k** [fablabnbg/Dokumente#34]
Für die Beitragsordnung ist eine Einrückung falsch und dann fängt die Nummerirung von vorn an, wenn man das pdf mit pandoc erzeugt. Bei dem zusatz der Ermäßigung:

[Beitrags-Gebuehrenordnung.pdf](https://github.com/fablabnbg/Dokumente/files/2283671/Beitrags-Gebuehrenordnung.pdf)

In GitHub ist das nicht.

**Comment by jnweiger** [comment]
Die Einrückung ist kaputtgegangen. Bitte wieder reparieren.

**Comment by Hobo2k** [comment]
@jnweiger 
Ich habe es wieder eingerückt, das geht, aber jetzt schreibt er den Absatz über den rand hinaus...
ursprünglich waren es 4 Leerzeichen
[Beitrags-Gebuehrenordnung.pdf](https://github.com/fablabnbg/Dokumente/files/2286508/Beitrags-Gebuehrenordnung.pdf)
, nach meiner Änderung waren es nur noch 3, das hat keine Abhilfe gebracht.

habe jetzt einen Tabulator, das geht jetzt mit Aufzählung etc. aber so ganz passt es leider immer noch nicht. Es ist jetzt nur noch einzeilig.
Ich steig da nicht mehr durch :-(

Können wir heute Abend mal schauen?
Danke.

**Comment by Hobo2k** [comment]
So geht jetzt endlich wieder.

[Beitrags-Gebuehrenordnung.pdf](https://github.com/fablabnbg/Dokumente/files/2289529/Beitrags-Gebuehrenordnung.pdf)
